### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by APratham** [kathir-t/QwiklabsProfileAnalyzer#2]
Please add a license and a CONTRIBUTING.md file to this repo. Adding a license will help regulate how people use your code and also a CONTRIBUTING.md file will help others know how to contribute to this project

**Comment by kathir-t** [comment]
LICENSE part has been done. I did not add any license since everything else, not just MY PART of the code, has to comply with the license. For instance, I think if something is licensed under GNU GPL v3, any modifications of that must also be licensed as the same GNU GPL v3. For now, without considering much, I have added _The Unlicense_ license. If you find any compliance issues, feel free to point out.
